name: Push to Another Repository

on:
  push:
    branches:
      - main  # 修改为适用的分支

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "jxpeng98"
          git config user.email "jiaxin.peng@outlook.com"
          git config --global push.default simple
          git remote add destination https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/jxpeng98/NotionNext-pjx.git
          git fetch origin
          git fetch destination
          git checkout -b temporary
          
      - name: Push changes
        run: |
          git checkout main
          git merge origin/main
          git push destination main

      - name: Cleanup
        run: |
          git checkout main
          git branch -D temporary
