name: Deploy to Docker

on:
  push:
    branches:
      - main  # or the default branch you use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-repo-name:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-repo-name:${{ github.sha }}

